//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwComprobanteCFDI
    {
        public string UUID { get; set; }
        public string TIPOCOMPROBANTE { get; set; }
        public string FOLIO { get; set; }
        public string FECHA { get; set; }
        public decimal TOTAL { get; set; }
        public string MONEDA { get; set; }
        public string METODOPAGO { get; set; }
        public string EMISOR_RFC { get; set; }
        public string RESUMENCFDI { get; set; }
        public string NOMBREARCHIVO { get; set; }
        public string CARPETAARCHIVO { get; set; }
        public short VALIDADO { get; set; }
        public string VCHRNMBR { get; set; }
        public short DOCTYPE { get; set; }
    }
}
